
export type CommunicationStyle = 'default' | 'rude' | 'cute' | 'intellectual' | 'friendly';
export type TaskType = 'daily' | 'goal';
export type TransactionType = 'income' | 'expense';
export type AssetType = 'cash' | 'bank' | 'crypto' | 'stock' | 'real_estate' | 'other';

export interface FriendRequest {
    fromUsername: string;
    fromId: string;
    fromAvatar: string;
    createdAt: string;
}

export interface MoodEntry {
    date: string; // yyyy-MM-dd
    value: number; // 1-6
}

export interface Habit {
    id: string;
    title: string;
    xpReward: number;
    createdAt: string;
    color: string;
}

export interface Transaction {
    id: string;
    amount: number;
    type: TransactionType;
    category: string;
    description?: string;
    date: string; // ISO date
    relatedTaskId?: string;
    receiptImage?: string; // Base64 of the receipt
}

export interface Asset {
    id: string;
    name: string;
    value: number;
    type: AssetType;
    currency: string;
}

export type MapRole = 'editor' | 'viewer'; // 'viewer' acts as Subordinate (can only edit assigned nodes)

export interface StructureInvite {
    id: string;
    mapId: string;
    mapTitle: string;
    inviter: string;
    role: MapRole;
}

export interface User {
  username: string;
  uniqueId: string; // Unique short code for finding friends
  password?: string; // Simple auth
  avatar: string; // URL or Emoji or Base64
  description: string; // Bio
  level: number;
  currentXP: number;
  maxXP: number;
  // gold removed
  totalTasksCompleted: number;
  missedTasks: number;
  communicationStyle: CommunicationStyle;
  themeId: string;
  appMode: 'standard' | 'advanced'; // NEW FIELD
  settings: {
    dailyMin: number;
    dailyMax: number;
    monthlyIncomeGoal: number; // New setting
  };
  // Social & Privacy
  friends: string[]; // List of usernames
  friendRequests: FriendRequest[]; // Incoming requests
  structureInvites: StructureInvite[]; // NEW: Map Invites
  affiliatedMapId?: string; // NEW: Linked "Workplace" / Structure
  privacyMode: 'public' | 'friends' | 'private';
  
  // Mood Tracking
  moodHistory: MoodEntry[];
  
  // Questing
  currentQuestId?: string; // ID of the quest the user is currently doing
  
  // Onboarding
  onboardingStep: number; // 0 = start, 1 = main goal, 2 = subgoals, 3 = deep dive, 4 = done
}

// "Skills" are now effectively "Categories" (Tags)
export interface Skill {
  id: string;
  parentId: string | null;
  name: string;
  color: string;
  level: number;
  currentXP: number;
  maxXP: number;
  requiredMoney?: number; // Cost to unlock/progress node
  deadline?: string; // ISO Date string for time-based planning
  startDate?: string; // ISO Date string
}

// --- NEW STRUCTURES TYPES ---
export type ConditionType = 'node' | 'balance' | 'task' | 'checklist';

export interface StructureCondition {
    id: string;
    type: ConditionType;
    targetId?: string; // Node ID (for 'node') or Task Title/Habit ID (for 'task'), Text label for Checklist
    value: number; // Required % (for node), Amount (for balance), Count (for task), 0/1 for checklist
}

export interface StructureMap {
    id: string;
    title: string;
    description?: string;
    avatar?: string; // NEW: Map Logo/Avatar
    ownerId?: string; // Username of creator
    members?: string[]; // List of usernames/virtual names
    roles?: Record<string, MapRole>; // Map of username -> role
    pendingInvites?: string[]; // List of usernames invited but pending
}

export interface StructureConnection {
    id: string;
    fromId: string;
    toId: string;
    mapId?: string; // Link to specific map
}

export interface StructureNode {
    id: string;
    title: string;
    description: string;
    color: string; // Kept for legacy/fallback, but UI will prefer skillId color
    skillId?: string; // Category Link
    x: number;
    y: number;
    width: number;
    height: number;
    conditions: StructureCondition[];
    deadline?: string; // Manual date
    mapId?: string; // Link to specific map
    assignees?: string[]; // List of usernames/virtual names responsible for this node
}
// -----------------------------

export interface TaskChecklistItem {
    id: string;
    text: string;
    completed: boolean;
}

export interface Task {
  id: string;
  type: TaskType;
  date?: string; // Only for daily
  deadline?: string; // Optional for daily, required for goals
  createdAt?: string; // Required for goal timers
  title: string;
  description: string;
  skillId: string; // Links to "Categories" (Skill)
  xpReward: number; // Max 20 for daily, 200 for goals
  completed: boolean;
  
  // New Fields
  startTime?: string; // HH:mm
  endTime?: string;   // HH:mm
  externalLink?: string; // URL

  linkedNoteId?: string;
  linkedConditionId?: string; // Specific condition within the node
  linkedInventoryId?: string; // Link to a Backpack
  checklist?: TaskChecklistItem[];
  habitId?: string; // If generated by a habit
}

export interface Note {
  id: string;
  title: string;
  content: string;
  images?: string[]; // Array of base64 strings
  createdAt: string;
}

// Updated Inventory Structures
export interface InventoryItem {
  id: string;
  text: string;
  checked: boolean;
  type?: 'text' | 'link';
}

export interface InventoryList {
    id: string;
    title: string;
    items: InventoryItem[];
}

export interface Quest {
  id: string;
  title: string;
  description: string;
  xpReward: number;
  status: 'available' | 'active' | 'completed' | 'failed';
  requirementType: 'task_count' | 'skill_level';
  requirementValue: number;
  requirementSkillId?: string; // If present, only tasks with this skill count
  currentProgress: number;
  isCustom?: boolean;
  betAmount?: number;
  deadline?: string;
}

export interface ShopItem {
  id: string;
  category: 'style' | 'theme';
  name: string;
  value: string; // style key or css class
  description: string;
}

export interface GameState {
  user: User | null;
  skills: Skill[]; // Categories
  structureMaps: StructureMap[]; // NEW: Multiple maps support
  structures: StructureNode[]; // Nodes
  structureConnections: StructureConnection[]; // Connections
  tasks: Task[];
  quests: Quest[];
  notes: Note[];
  inventory: InventoryList[]; // Changed to array of Lists (Backpacks)
  shopItems: ShopItem[];
  habits: Habit[];
  transactions: Transaction[];
  assets: Asset[];
  showLevelUp: boolean;
  xpGain: { amount: number; x: number; y: number } | null; // For animation
}

export type GameAction =
  | { type: 'LOAD_GAME'; payload: GameState }
  | { type: 'LOGOUT' }
  | { type: 'UPDATE_PROFILE'; payload: { avatar: string; description: string } }
  | { type: 'ADD_TASK'; payload: Task }
  | { type: 'ADD_TASKS_BATCH'; payload: Task[] } 
  | { type: 'UPDATE_TASK'; payload: Task }
  | { type: 'DELETE_TASK'; payload: string }
  | { type: 'UPDATE_TASK_DATE'; payload: { id: string; date: string } } 
  | { type: 'UPDATE_TASK_CHECKLIST'; payload: { taskId: string; checklist: TaskChecklistItem[] } }
  | { type: 'TOGGLE_TASK'; payload: { id: string; x?: number; y?: number } } 
  | { type: 'ADD_SKILL'; payload: Skill }
  | { type: 'ADD_SKILLS_BATCH'; payload: Skill[] }
  | { type: 'UPDATE_SKILL'; payload: Skill } 
  | { type: 'DELETE_SKILL'; payload: string }
  | { type: 'RESET_SKILLS' }
  
  // Structures Actions
  | { type: 'ADD_STRUCTURE_MAP'; payload: StructureMap }
  | { type: 'DELETE_STRUCTURE_MAP'; payload: string }
  | { type: 'UPDATE_STRUCTURE_MAP'; payload: StructureMap }
  | { type: 'ADD_STRUCTURE'; payload: StructureNode }
  | { type: 'UPDATE_STRUCTURE'; payload: StructureNode }
  | { type: 'DELETE_STRUCTURE'; payload: string }
  | { type: 'ADD_STRUCTURE_CONNECTION'; payload: StructureConnection }
  | { type: 'DELETE_STRUCTURE_CONNECTION'; payload: string }
  | { type: 'INVITE_TO_MAP'; payload: { mapId: string; targetUsername: string; isVirtual: boolean; role: MapRole } }
  | { type: 'ACCEPT_MAP_INVITE'; payload: StructureInvite }
  | { type: 'REJECT_MAP_INVITE'; payload: string } // Invite ID
  | { type: 'REMOVE_MAP_MEMBER'; payload: { mapId: string; username: string } }
  | { type: 'SET_AFFILIATION'; payload: string | undefined } // New Action

  | { type: 'ACCEPT_QUEST'; payload: string }
  | { type: 'CREATE_CUSTOM_QUEST'; payload: Quest }
  | { type: 'COMPLETE_QUEST'; payload: string }
  | { type: 'FAIL_QUEST'; payload: string }
  | { type: 'UPDATE_SETTINGS'; payload: { min?: number; max?: number; incomeGoal?: number } }
  | { type: 'ADD_NOTE'; payload: Note }
  | { type: 'UPDATE_NOTE'; payload: { id: string; title: string; content: string; images?: string[] } }
  | { type: 'DELETE_NOTE'; payload: string }
  // Inventory Actions (Updated)
  | { type: 'ADD_INVENTORY_LIST'; payload: InventoryList }
  | { type: 'DELETE_INVENTORY_LIST'; payload: string }
  | { type: 'UPDATE_INVENTORY_LIST_NAME'; payload: { id: string; name: string } }
  | { type: 'ADD_INVENTORY_ITEM'; payload: { listId: string; item: InventoryItem } }
  | { type: 'TOGGLE_INVENTORY_ITEM'; payload: { listId: string; itemId: string } }
  | { type: 'DELETE_INVENTORY_ITEM'; payload: { listId: string; itemId: string } }
  
  | { type: 'EQUIP_ITEM'; payload: { category: 'style' | 'theme'; value: string } }
  | { type: 'CLOSE_LEVEL_UP' }
  | { type: 'CLEAR_XP_ANIMATION' }
  | { type: 'UPDATE_PRIVACY'; payload: 'public' | 'friends' | 'private' }
  | { type: 'SEND_FRIEND_REQUEST'; payload: string } 
  | { type: 'ACCEPT_FRIEND_REQUEST'; payload: string } 
  | { type: 'REJECT_FRIEND_REQUEST'; payload: string } 
  | { type: 'REMOVE_FRIEND'; payload: string }
  | { type: 'LOG_MOOD'; payload: number }
  | { type: 'ADD_HABIT'; payload: Habit }
  | { type: 'DELETE_HABIT'; payload: string }
  | { type: 'ADD_TRANSACTION'; payload: Transaction }
  | { type: 'DELETE_TRANSACTION'; payload: string }
  | { type: 'ADD_ASSET'; payload: Asset }
  | { type: 'DELETE_ASSET'; payload: string }
  | { type: 'UPDATE_ASSET'; payload: Asset }
  | { type: 'SET_ONBOARDING_STEP'; payload: number }
  | { type: 'SET_APP_MODE'; payload: 'standard' | 'advanced' };
